name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop and remove existing container (if running)
        run: |
          whoami
          docker stop my-server-container || true
          docker rm my-server-container || true

      - name: Build and run new container
        run: |
          docker build -t pixel-crypt-img:latest .
          docker run -d --name pixel-crypt -p 80:80 my-server-image:latest
